name: Pacakge
on:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create NPM Pacakge
        run: |
          git branch -d npm &> /dev/null || echo upm branch not found
          git checkout -b npm
          git push -f -u origin npm
      - name: Create upm git tag
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git tag $TAG upm
          git push origin --tags
        env:
          TAG: upm/v${{ steps.semantic.outputs.new_release_version }}
